name: Auto Merge PR

on:
    pull_request:
        types: [opened, reopened]
        
jobs:
    
    merge:
        if: github.actor == 'AleksandrGnatiuk' || github.actor == 'test_user'
        runs-on: ubuntu-latest
        steps:
        
        - uses: action/checkout@v1
        
        - uses: hmarr/auto-approve-action@v2.0.0
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            
        - uses: managedkaos/merge-pull-request@1.2
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
        